name: Android CI

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout
        uses: actions/checkout@v4

      # Step 2: Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      # Step 3: Cache Gradle dependencies
      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Step 4: Run ktlint (code style)
      - name: Run ktlint
        run: ./gradlew ktlintCheck --stacktrace

      # Step 5: Run detekt (static analysis)
      - name: Run detekt
        run: ./gradlew detekt --stacktrace

      # Step 6: Build Debug APK
      - name: Build Debug APK
        run: ./gradlew assembleDebug --stacktrace --info

      # Step 7: Run Unit Tests
      - name: Run Unit Tests
        run: ./gradlew test --stacktrace

      # Step 8: Upload APK artifact
      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: app/build/outputs/**/*.apk

  instrumented:
    runs-on: macos-latest
    needs: build   # wait for build job

    steps:
      # Step 1: Checkout code
      - name: Checkout
        uses: actions/checkout@v4

      # Step 2: Set up JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3


          # Step 3: Run emulator + connected tests
      - name: Run Instrumented Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 26
          target: default
          arch: x86_64
          profile: Nexus 4
          emulator-boot-timeout: 1200   # timeout in seconds (15 minutes)
          emulator-options: -no-snapshot-load -no-window -no-audio -no-boot-anim
          script: |
            adb wait-for-device
            adb shell input keyevent 82
            ./gradlew connectedAndroidTest --continue
     

      - name: Upload Test Reports
        if: failure()
        uses: actions/upload-artifact@v4
        with:
                name: android-test-report
                path: '**/build/reports/androidTests/connected/'